var dir_46a83dbd80efd788dd244119c0399a75 =
[
    [ "SenClientAvatar.h", "SenClientAvatar_8h_source.html", null ],
    [ "SenClientBoxArt.h", "SenClientBoxArt_8h_source.html", null ],
    [ "SenClientConfig.h", "SenClientConfig_8h_source.html", null ],
    [ "SenClientCore.h", "SenClientCore_8h_source.html", null ],
    [ "SenClientCulture.h", "SenClientCulture_8h_source.html", null ],
    [ "SenClientCultureBackCompat_SenBoxArt.h", "SenClientCultureBackCompat__SenBoxArt_8h_source.html", null ],
    [ "SenClientCultureBackCompat_SenClientUGC.h", "SenClientCultureBackCompat__SenClientUGC_8h_source.html", null ],
    [ "SenClientCultureBackCompat_SenCore.h", "SenClientCultureBackCompat__SenCore_8h_source.html", null ],
    [ "SenClientCultureBackCompat_SenNews.h", "SenClientCultureBackCompat__SenNews_8h_source.html", null ],
    [ "SenClientCultureBackCompat_SenSuperstars.h", "SenClientCultureBackCompat__SenSuperstars_8h_source.html", null ],
    [ "SenClientDynamicConfig.h", "SenClientDynamicConfig_8h_source.html", null ],
    [ "SenClientFame.h", "SenClientFame_8h_source.html", null ],
    [ "SenClientFile.h", "SenClientFile_8h_source.html", null ],
    [ "SenClientHelp.h", "SenClientHelp_8h_source.html", null ],
    [ "SenClientMain.h", "SenClientMain_8h_source.html", null ],
    [ "SenClientMarkers.h", "SenClientMarkers_8h_source.html", null ],
    [ "SenClientNews.h", "SenClientNews_8h_source.html", null ],
    [ "SenClientPackage.h", "SenClientPackage_8h_source.html", null ],
    [ "SenClientRawData.h", "SenClientRawData_8h_source.html", null ],
    [ "SenClientResource.h", "SenClientResource_8h_source.html", null ],
    [ "SenClientStats.h", "SenClientStats_8h_source.html", null ],
    [ "SenClientSuperstars.h", "SenClientSuperstars_8h_source.html", null ],
    [ "SenClientSys.h", "SenClientSys_8h_source.html", null ],
    [ "SenClientTypes.h", "SenClientTypes_8h_source.html", null ],
    [ "SenClientUGC.h", "SenClientUGC_8h_source.html", null ],
    [ "SenClientUGCLeaderboards.h", "SenClientUGCLeaderboards_8h_source.html", null ],
    [ "SenClientUGCTypes.h", "SenClientUGCTypes_8h_source.html", null ],
    [ "SenClientUser.h", "SenClientUser_8h_source.html", null ],
    [ "SenClientUtil.h", "SenClientUtil_8h_source.html", null ],
    [ "SenClientXML.h", "SenClientXML_8h_source.html", null ]
];