var dir_46a83dbd80efd788dd244119c0399a75 =
[
    [ "SenClientAvatar.h", "SenClientAvatar_8h.html", "SenClientAvatar_8h" ],
    [ "SenClientBoxArt.h", "SenClientBoxArt_8h.html", "SenClientBoxArt_8h" ],
    [ "SenClientConfig.h", "SenClientConfig_8h.html", "SenClientConfig_8h" ],
    [ "SenClientCore.h", "SenClientCore_8h.html", null ],
    [ "SenClientCulture.h", "SenClientCulture_8h.html", "SenClientCulture_8h" ],
    [ "SenClientCultureBackCompat_SenBoxArt.h", "SenClientCultureBackCompat__SenBoxArt_8h.html", "SenClientCultureBackCompat__SenBoxArt_8h" ],
    [ "SenClientCultureBackCompat_SenClientUGC.h", "SenClientCultureBackCompat__SenClientUGC_8h.html", "SenClientCultureBackCompat__SenClientUGC_8h" ],
    [ "SenClientCultureBackCompat_SenCore.h", "SenClientCultureBackCompat__SenCore_8h.html", "SenClientCultureBackCompat__SenCore_8h" ],
    [ "SenClientCultureBackCompat_SenNews.h", "SenClientCultureBackCompat__SenNews_8h.html", "SenClientCultureBackCompat__SenNews_8h" ],
    [ "SenClientCultureBackCompat_SenSuperstars.h", "SenClientCultureBackCompat__SenSuperstars_8h.html", "SenClientCultureBackCompat__SenSuperstars_8h" ],
    [ "SenClientDynamicConfig.h", "SenClientDynamicConfig_8h.html", null ],
    [ "SenClientFame.h", "SenClientFame_8h.html", "SenClientFame_8h" ],
    [ "SenClientFile.h", "SenClientFile_8h.html", "SenClientFile_8h" ],
    [ "SenClientHelp.h", "SenClientHelp_8h.html", null ],
    [ "SenClientMain.h", "SenClientMain_8h.html", "SenClientMain_8h" ],
    [ "SenClientMarkers.h", "SenClientMarkers_8h.html", "SenClientMarkers_8h" ],
    [ "SenClientNews.h", "SenClientNews_8h.html", "SenClientNews_8h" ],
    [ "SenClientPackage.h", "SenClientPackage_8h.html", "SenClientPackage_8h" ],
    [ "SenClientRawData.h", "SenClientRawData_8h.html", "SenClientRawData_8h" ],
    [ "SenClientResource.h", "SenClientResource_8h.html", "SenClientResource_8h" ],
    [ "SenClientStats.h", "SenClientStats_8h.html", "SenClientStats_8h" ],
    [ "SenClientSuperstars.h", "SenClientSuperstars_8h.html", null ],
    [ "SenClientSys.h", "SenClientSys_8h.html", "SenClientSys_8h" ],
    [ "SenClientTypes.h", "SenClientTypes_8h.html", "SenClientTypes_8h" ],
    [ "SenClientUGC.h", "SenClientUGC_8h.html", "SenClientUGC_8h" ],
    [ "SenClientUGCLeaderboards.h", "SenClientUGCLeaderboards_8h.html", "SenClientUGCLeaderboards_8h" ],
    [ "SenClientUGCTypes.h", "SenClientUGCTypes_8h.html", "SenClientUGCTypes_8h" ],
    [ "SenClientUser.h", "SenClientUser_8h.html", "SenClientUser_8h" ],
    [ "SenClientUtil.h", "SenClientUtil_8h.html", "SenClientUtil_8h" ],
    [ "SenClientXML.h", "SenClientXML_8h.html", "SenClientXML_8h" ]
];