#pragma once

#define VER_PRODUCTBUILD 560
#define VER_PRODUCTVERSION_STR_W L"TU19"
#define VER_FILEVERSION_STR_W VER_PRODUCTVERSION_STR_W
#define VER_BRANCHVERSION_STR_W L"RELEASE"
#define VER_NETWORK VER_PRODUCTBUILD
